### ISSUE TITLE
metalnx-msi does not work with iRODS 4.2

### ISSUE THREAD

**Issue by sgworth** [Metalnx/metalnx-msi#1]
Following setup of metalnx-msi on a Centos 7 system with iRODS 4.2 (provider mode) the data extraction micro services do not fire.  I tried moving them into the new micro service location at /usr/lib/irods/plugins/microservices, but got the same result.

**Comment by ajguerra** [comment]
iRODS 4.2 changed the way to compile microservices. They've changed some libraries, directories and added cmake as their build manager process. We are already aware of that and we're working on it,

**Comment by ajguerra** [comment]
Check out version 1.2.0. We now support iRODS 4.2.0.
